# Generated by Django 4.2.3 on 2023-07-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPI',
        ),
    ]
