# Generated by Django 4.2.3 on 2023-07-25 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0008_team_game_away_team_game_home_team_game_loser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='rpiapp.season'),
        ),
    ]
