# Generated by Django 4.2.3 on 2023-07-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0009_alter_game_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season', to='rpiapp.season'),
        ),
    ]
