# Generated by Django 4.2.3 on 2023-08-10 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpiapp', '0014_game_user_games_league_user_leagues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_games',
        ),
        migrations.RemoveField(
            model_name='league',
            name='user_leagues',
        ),
        migrations.RemoveField(
            model_name='season',
            name='user_teams',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_teams',
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_seasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
