# Generated by Django 4.2.3 on 2023-08-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0016_alter_game_created_by_alter_league_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('league', 'name')},
        ),
    ]
