# Generated by Django 4.2.3 on 2023-08-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0017_alter_league_name_alter_season_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date of season'),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date of season'),
        ),
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
    ]
