# Generated by Django 4.2.3 on 2023-08-18 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0019_season_name_alter_season_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpi', models.DecimalField(decimal_places=6, max_digits=7)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rpis', to='rpiapp.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_rpis', to='rpiapp.team')),
            ],
        ),
    ]
