# Generated by Django 4.2.3 on 2023-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0020_rpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bulk_processing',
            field=models.BooleanField(default=False),
        ),
    ]
