# Generated by Django 4.2.3 on 2023-08-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0021_game_bulk_processing'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='high_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='league',
            name='location_matters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='league',
            name='low_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='league',
            name='oowp_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='league',
            name='owp_weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.CharField(choices=[('baseball', 'Baseball'), ('basketball', 'Basketball'), ('football', 'Football'), ('hockey', 'Hockey'), ('custom', 'Custom')], default='baseball', max_length=100),
        ),
        migrations.AddField(
            model_name='league',
            name='wp_weight',
            field=models.FloatField(default=0.25),
        ),
    ]
