# Generated by Django 4.2.3 on 2023-08-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0022_league_high_weight_league_location_matters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='high_weight',
        ),
        migrations.RemoveField(
            model_name='league',
            name='location_matters',
        ),
        migrations.RemoveField(
            model_name='league',
            name='low_weight',
        ),
        migrations.RemoveField(
            model_name='league',
            name='oowp_weight',
        ),
        migrations.RemoveField(
            model_name='league',
            name='owp_weight',
        ),
        migrations.RemoveField(
            model_name='league',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='league',
            name='wp_weight',
        ),
        migrations.AddField(
            model_name='season',
            name='high_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='season',
            name='location_matters',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='low_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='season',
            name='oowp_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='season',
            name='owp_weight',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='season',
            name='wp_weight',
            field=models.FloatField(default=0.25),
        ),
    ]
