# Generated by Django 4.2.3 on 2023-08-22 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0024_league_sport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('league', 'name', 'start_date', 'end_date')},
        ),
    ]
