# Generated by Django 4.2.3 on 2023-08-30 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpiapp', '0025_alter_season_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='sport',
        ),
    ]
